CREATE TABLE users (
	bio VARCHAR(500),
	date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	date_of_birth DATE,
	date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	email VARCHAR(50) NOT NULL,
	full_name VARCHAR(50),
	gender VARCHAR(20),
	uid VARCHAR(30) PRIMARY KEY
);

CREATE TABLE accounts (
	date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id BIGSERIAL PRIMARY KEY,
    provider_id VARCHAR(30) NOT NULL,
    uid VARCHAR(30) NOT NULL REFERENCES users
);

CREATE TABLE workout_logs (
    calories_burnt INTEGER,
    date DATE NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    duration INTEGER,
    id BIGSERIAL PRIMARY KEY,
    intensity VARCHAR(10),
    title VARCHAR(50) NOT NULL,
    uid VARCHAR(30) NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE strength_training (
    date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id BIGSERIAL PRIMARY KEY,
    index INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    reps INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    weight INTEGER,
    workout_log_id BIGSERIAL NOT NULL REFERENCES workout_logs ON DELETE CASCADE
);

CREATE TABLE runs (
    date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    distance INTEGER NOT NULL,
    duration INTEGER NOT NULL,
    id BIGSERIAL PRIMARY KEY,
    index INTEGER NOT NULL,
    workout_log_id BIGSERIAL NOT NULL REFERENCES workout_logs ON DELETE CASCADE
);

CREATE TABLE devices (
    date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    device_token TEXT NOT NULL,
    id BIGSERIAL PRIMARY KEY,
    uid VARCHAR(30) NOT NULL REFERENCES users ON DELETE CASCADE
);

ALTER TABLE "public"."workout_logs"
ADD COLUMN "workout_type" varchar(50) NOT NULL;

CREATE TABLE scheduled (
    body VARCHAR(500) NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id BIGSERIAL PRIMARY KEY,
    scheduled_time TIMESTAMPTZ NOT NULL,
    title VARCHAR(30) NOT NULL,
    uid VARCHAR(30) NOT NULL REFERENCES users ON DELETE CASCADE
);