CREATE TABLE users (
	date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	email TEXT NOT NULL UNIQUE,
	full_name TEXT NOT NULL,
	uid TEXT PRIMARY KEY
);
