CREATE TABLE users (
	date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	email TEXT NOT NULL UNIQUE,
	full_name TEXT NOT NULL,
	uid TEXT PRIMARY KEY
);

CREATE TABLE transactions (
	amount BIGINT NOT NULL,
	category INT NOT NULL,
	date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name TEXT NOT NULL,
	user_id TEXT NOT NULL REFERENCES users ON DELETE CASCADE
);
