spring:
    application:
        name: tutor_buddy_app
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        url: ${DATABASE_URL}
logging:
    level:
        com.wenjun.astra_persistence.mappers: DEBUG
firebaseServiceAccount: ${FIREBASE_SERVICE_ACCOUNT}
baseUrl: ${BASE_URL}